### ISSUE TITLE
[Feature Request]: fixing type annotations

### ISSUE THREAD

**Issue by davorrunje** [microsoft/autogen#1462]
### Is your feature request related to a problem? Please describe.

When extending the framework, developers use typing information from existing code. However, this information is sometimes incomplete (e.g. parameters having type annotations `List` without specifying if is it a list of strings or dictionaries) or sometimes even wrong (functions change over time and sometimes type annotations are not properly updated). It also makes testing difficult because it is not always clear which cases need to be checked.

A good way to enforce correctness of the type annotations would be to ensure mypy check passes. Currently, running it on autogen with the configuration below yields over 1000 errors.

### Describe the solution you'd like

1. Add the following configuration to pyproject.toml:
```toml
[tool.mypy]

strict = true
python_version = "3.8"
ignore_missing_imports = true
install_types = true
non_interactive = true
plugins = [
    "pydantic.mypy"
]

# makes it easer to incrementally fix file by file
follow_imports = "silent"

# from https://blog.wolt.com/engineering/2021/09/30/professional-grade-mypy-configuration/
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
warn_unused_ignores = true

disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_any_unimported = true
```

2. Fix type annotations in related groups of changed files in multiple PRs.
