### ISSUE TITLE
[Issue]: user_proxy can't run code in docker

### ISSUE THREAD

**Issue by yidasanqian** [microsoft/autogen#3036]
### Describe the issue

test follow default workflow
![image](https://github.com/microsoft/autogen/assets/10655188/392d82f3-7ec7-4d2d-915b-627eeafd4515)

Found an issue: 
user_proxy can't run code in docker， Stuck at ” user_proxy (to default_assistant):“

### Steps to reproduce

step1. run AutoGen Studio in a Docker container. 
step2. Configure user proxy to run code using Docker.
![image](https://github.com/microsoft/autogen/assets/10655188/7e3d3a55-900b-4494-9942-328bac671987)

step3. run test default workflow
![image](https://github.com/microsoft/autogen/assets/10655188/392d82f3-7ec7-4d2d-915b-627eeafd4515)

step4. checking the logs in a Docker:
![image](https://github.com/microsoft/autogen/assets/10655188/2c864df1-d1be-4bdb-9de3-10313bd89981)

### Additional Information

Operating System: win11
[dockerfile:](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/Dockerfile)
```
FROM python:3.10

WORKDIR /code

RUN pip install -U gunicorn autogenstudio

RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH \
    AUTOGENSTUDIO_APPDIR=/home/user/app

WORKDIR $HOME/app

COPY --chown=user . $HOME/app

CMD gunicorn -w $((2 * $(getconf _NPROCESSORS_ONLN) + 1)) --timeout 12600 -k uvicorn.workers.UvicornWorker autogenstudio.web.app:app --bind "0.0.0.0:8081"
```
docker compose:
```
services:
  autogen-studio-ui:
    image: autogen_studio_image
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DOCKER_HOST=tcp://localhost:2375      
    volumes:
      - ./data:/home/user/app
```
