### ISSUE TITLE
Add authentication infrastructure for AGS

### ISSUE THREAD

**Issue by victordibia** [microsoft/autogen#4350]
Currently AGS lacks authentication, limiting its use in multi-user environments. We need to add authentication while maintaining ease of use.

## Requirements
1. Add auth for API routes and WebSocket connections
2. Default mode: Works without configuration using local authentication (username/password)
3. Support for configurable OAuth providers (GitHub, Microsoft, etc.) 
4. Update UI to load and apply auth config profiles etc.
5. Optional RBAC support? 
## Potential Approach (subject to change)
- FastAPI security dependencies for route protection
- Local auth with configurable admin credentials
- OAuth provider configuration via `auth_config.yaml`:
```yaml
auth:
  enabled: true
  providers:
    local:
      enabled: true
      admin_user: admin
      admin_pass: changeme
    github:
      enabled: false
      client_id: ""
      client_secret: ""
...
```
